/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PrivacyPresale {
  export type OptionsStruct = {
    tokenPresale: BigNumberish;
    tokenAddLiquidity: BigNumberish;
    softCap: BigNumberish;
    hardCap: BigNumberish;
    minContribution: BigNumberish;
    maxContribution: BigNumberish;
    start: BigNumberish;
    end: BigNumberish;
    liquidityPercentage: BigNumberish;
    listingRate: BigNumberish;
  };

  export type OptionsStructOutput = [
    tokenPresale: bigint,
    tokenAddLiquidity: bigint,
    softCap: bigint,
    hardCap: bigint,
    minContribution: bigint,
    maxContribution: bigint,
    start: bigint,
    end: bigint,
    liquidityPercentage: bigint,
    listingRate: bigint
  ] & {
    tokenPresale: bigint;
    tokenAddLiquidity: bigint;
    softCap: bigint;
    hardCap: bigint;
    minContribution: bigint;
    maxContribution: bigint;
    start: bigint;
    end: bigint;
    liquidityPercentage: bigint;
    listingRate: bigint;
  };
}

export interface PrivacyPresaleFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createPrivacyPresaleWithExistingToken"
      | "cweth"
      | "getPresales"
      | "presales"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PrivacyPresaleCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createPrivacyPresaleWithExistingToken",
    values: [AddressLike, PrivacyPresale.OptionsStruct]
  ): string;
  encodeFunctionData(functionFragment: "cweth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getPresales",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "presales",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createPrivacyPresaleWithExistingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cweth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPresales",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "presales", data: BytesLike): Result;
}

export namespace PrivacyPresaleCreatedEvent {
  export type InputTuple = [
    creator: AddressLike,
    presale: AddressLike,
    token: AddressLike,
    ctoken: AddressLike,
    cweth: AddressLike
  ];
  export type OutputTuple = [
    creator: string,
    presale: string,
    token: string,
    ctoken: string,
    cweth: string
  ];
  export interface OutputObject {
    creator: string;
    presale: string;
    token: string;
    ctoken: string;
    cweth: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivacyPresaleFactory extends BaseContract {
  connect(runner?: ContractRunner | null): PrivacyPresaleFactory;
  waitForDeployment(): Promise<this>;

  interface: PrivacyPresaleFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createPrivacyPresaleWithExistingToken: TypedContractMethod<
    [_token: AddressLike, _options: PrivacyPresale.OptionsStruct],
    [string],
    "nonpayable"
  >;

  cweth: TypedContractMethod<[], [string], "view">;

  getPresales: TypedContractMethod<[], [string[]], "view">;

  presales: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createPrivacyPresaleWithExistingToken"
  ): TypedContractMethod<
    [_token: AddressLike, _options: PrivacyPresale.OptionsStruct],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cweth"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPresales"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "presales"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "PrivacyPresaleCreated"
  ): TypedContractEvent<
    PrivacyPresaleCreatedEvent.InputTuple,
    PrivacyPresaleCreatedEvent.OutputTuple,
    PrivacyPresaleCreatedEvent.OutputObject
  >;

  filters: {
    "PrivacyPresaleCreated(address,address,address,address,address)": TypedContractEvent<
      PrivacyPresaleCreatedEvent.InputTuple,
      PrivacyPresaleCreatedEvent.OutputTuple,
      PrivacyPresaleCreatedEvent.OutputObject
    >;
    PrivacyPresaleCreated: TypedContractEvent<
      PrivacyPresaleCreatedEvent.InputTuple,
      PrivacyPresaleCreatedEvent.OutputTuple,
      PrivacyPresaleCreatedEvent.OutputObject
    >;
  };
}
