/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFHERC20__factory } from "./IFHERC20__factory";
export { IPrivacyPresale__factory } from "./IPrivacyPresale__factory";
