/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPrivacyPresale,
  IPrivacyPresaleInterface,
} from "../../../contracts/interfaces/IPrivacyPresale";

const _abi = [
  {
    inputs: [],
    name: "InvalidCapValue",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "state",
        type: "uint8",
      },
    ],
    name: "InvalidState",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidTimestampValue",
    type: "error",
  },
  {
    inputs: [],
    name: "NotInPurchasePeriod",
    type: "error",
  },
  {
    inputs: [],
    name: "NotRefundable",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalTokens",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "addLiquidityTokens",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "presaleTokens",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "PoolInitialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
    ],
    name: "TokensPurchased",
    type: "event",
  },
] as const;

export class IPrivacyPresale__factory {
  static readonly abi = _abi;
  static createInterface(): IPrivacyPresaleInterface {
    return new Interface(_abi) as IPrivacyPresaleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPrivacyPresale {
    return new Contract(address, _abi, runner) as unknown as IPrivacyPresale;
  }
}
