/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type InEuint128Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint128StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export declare namespace PrivacyPresale {
  export type OptionsStruct = {
    tokenPresale: BigNumberish;
    tokenAddLiquidity: BigNumberish;
    softCap: BigNumberish;
    hardCap: BigNumberish;
    minContribution: BigNumberish;
    maxContribution: BigNumberish;
    start: BigNumberish;
    end: BigNumberish;
    liquidityPercentage: BigNumberish;
    listingRate: BigNumberish;
  };

  export type OptionsStructOutput = [
    tokenPresale: bigint,
    tokenAddLiquidity: bigint,
    softCap: bigint,
    hardCap: bigint,
    minContribution: bigint,
    maxContribution: bigint,
    start: bigint,
    end: bigint,
    liquidityPercentage: bigint,
    listingRate: bigint
  ] & {
    tokenPresale: bigint;
    tokenAddLiquidity: bigint;
    softCap: bigint;
    hardCap: bigint;
    minContribution: bigint;
    maxContribution: bigint;
    start: bigint;
    end: bigint;
    liquidityPercentage: bigint;
    listingRate: bigint;
  };
}

export interface PrivacyPresaleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowFinalizationDecrypt"
      | "claim"
      | "claimableTokens"
      | "contributions"
      | "finalizePreSale"
      | "getEthRaisedEncrypted"
      | "getTokensSoldEncrypted"
      | "owner"
      | "pool"
      | "purchase"
      | "refund"
      | "renounceOwnership"
      | "transferOwnership"
      | "viewClaimableTokens"
      | "viewContribution"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PoolInitialized"
      | "TokensPurchased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowFinalizationDecrypt",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimableTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contributions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizePreSale",
    values: [BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEthRaisedEncrypted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokensSoldEncrypted",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "purchase",
    values: [InEuint128Struct]
  ): string;
  encodeFunctionData(functionFragment: "refund", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "viewClaimableTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "viewContribution",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allowFinalizationDecrypt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimableTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizePreSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEthRaisedEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokensSoldEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "purchase", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewClaimableTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewContribution",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolInitializedEvent {
  export type InputTuple = [
    owner: AddressLike,
    totalTokens: BigNumberish,
    addLiquidityTokens: BigNumberish,
    presaleTokens: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    totalTokens: bigint,
    addLiquidityTokens: bigint,
    presaleTokens: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    owner: string;
    totalTokens: bigint;
    addLiquidityTokens: bigint;
    presaleTokens: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensPurchasedEvent {
  export type InputTuple = [beneficiary: AddressLike];
  export type OutputTuple = [beneficiary: string];
  export interface OutputObject {
    beneficiary: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivacyPresale extends BaseContract {
  connect(runner?: ContractRunner | null): PrivacyPresale;
  waitForDeployment(): Promise<this>;

  interface: PrivacyPresaleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowFinalizationDecrypt: TypedContractMethod<[], [void], "nonpayable">;

  claim: TypedContractMethod<[], [void], "nonpayable">;

  claimableTokens: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  contributions: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  finalizePreSale: TypedContractMethod<
    [
      cwethRaised: BigNumberish,
      ethRaisedSignature: BytesLike,
      tokensSold: BigNumberish,
      tokensSoldSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEthRaisedEncrypted: TypedContractMethod<[], [string], "view">;

  getTokensSoldEncrypted: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pool: TypedContractMethod<
    [],
    [
      [
        string,
        string,
        string,
        string,
        PrivacyPresale.OptionsStructOutput,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        presaleOwner: string;
        cweth: string;
        ctoken: string;
        token: string;
        options: PrivacyPresale.OptionsStructOutput;
        ethRaisedEncrypted: string;
        tokensSoldEncrypted: string;
        weiRaised: bigint;
        tokensSold: bigint;
        tokenPerEthWithDecimals: bigint;
        state: bigint;
      }
    ],
    "view"
  >;

  purchase: TypedContractMethod<
    [encryptedAmount: InEuint128Struct],
    [void],
    "nonpayable"
  >;

  refund: TypedContractMethod<[], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  viewClaimableTokens: TypedContractMethod<
    [account: AddressLike],
    [string],
    "view"
  >;

  viewContribution: TypedContractMethod<
    [account: AddressLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowFinalizationDecrypt"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimableTokens"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "contributions"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "finalizePreSale"
  ): TypedContractMethod<
    [
      cwethRaised: BigNumberish,
      ethRaisedSignature: BytesLike,
      tokensSold: BigNumberish,
      tokensSoldSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEthRaisedEncrypted"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTokensSoldEncrypted"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pool"
  ): TypedContractMethod<
    [],
    [
      [
        string,
        string,
        string,
        string,
        PrivacyPresale.OptionsStructOutput,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        presaleOwner: string;
        cweth: string;
        ctoken: string;
        token: string;
        options: PrivacyPresale.OptionsStructOutput;
        ethRaisedEncrypted: string;
        tokensSoldEncrypted: string;
        weiRaised: bigint;
        tokensSold: bigint;
        tokenPerEthWithDecimals: bigint;
        state: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "purchase"
  ): TypedContractMethod<
    [encryptedAmount: InEuint128Struct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "viewClaimableTokens"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "viewContribution"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolInitialized"
  ): TypedContractEvent<
    PoolInitializedEvent.InputTuple,
    PoolInitializedEvent.OutputTuple,
    PoolInitializedEvent.OutputObject
  >;
  getEvent(
    key: "TokensPurchased"
  ): TypedContractEvent<
    TokensPurchasedEvent.InputTuple,
    TokensPurchasedEvent.OutputTuple,
    TokensPurchasedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolInitialized(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      PoolInitializedEvent.InputTuple,
      PoolInitializedEvent.OutputTuple,
      PoolInitializedEvent.OutputObject
    >;
    PoolInitialized: TypedContractEvent<
      PoolInitializedEvent.InputTuple,
      PoolInitializedEvent.OutputTuple,
      PoolInitializedEvent.OutputObject
    >;

    "TokensPurchased(address)": TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;
    TokensPurchased: TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;
  };
}
