/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type InEuint128Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint128StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export interface IFHERC20Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "_transferEncrypted"
      | "_transferFromEncrypted"
      | "allowanceEncrypted"
      | "approveEncrypted"
      | "balanceOfEncrypted"
      | "transferEncrypted"
      | "transferFromEncrypted"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ApprovalEncrypted" | "TransferEncrypted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "_transferEncrypted",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "_transferFromEncrypted",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowanceEncrypted",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveEncrypted",
    values: [AddressLike, InEuint128Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfEncrypted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferEncrypted",
    values: [AddressLike, InEuint128Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFromEncrypted",
    values: [AddressLike, AddressLike, InEuint128Struct]
  ): string;

  decodeFunctionResult(
    functionFragment: "_transferEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_transferFromEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowanceEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFromEncrypted",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEncryptedEvent {
  export type InputTuple = [owner: AddressLike, spender: AddressLike];
  export type OutputTuple = [owner: string, spender: string];
  export interface OutputObject {
    owner: string;
    spender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEncryptedEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IFHERC20 extends BaseContract {
  connect(runner?: ContractRunner | null): IFHERC20;
  waitForDeployment(): Promise<this>;

  interface: IFHERC20Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _transferEncrypted: TypedContractMethod<
    [to: AddressLike, value: BytesLike],
    [string],
    "nonpayable"
  >;

  _transferFromEncrypted: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BytesLike],
    [string],
    "nonpayable"
  >;

  allowanceEncrypted: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [string],
    "view"
  >;

  approveEncrypted: TypedContractMethod<
    [spender: AddressLike, value: InEuint128Struct],
    [boolean],
    "nonpayable"
  >;

  balanceOfEncrypted: TypedContractMethod<
    [account: AddressLike],
    [string],
    "view"
  >;

  transferEncrypted: TypedContractMethod<
    [to: AddressLike, value: InEuint128Struct],
    [string],
    "nonpayable"
  >;

  transferFromEncrypted: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: InEuint128Struct],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_transferEncrypted"
  ): TypedContractMethod<
    [to: AddressLike, value: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "_transferFromEncrypted"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowanceEncrypted"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "approveEncrypted"
  ): TypedContractMethod<
    [spender: AddressLike, value: InEuint128Struct],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOfEncrypted"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "transferEncrypted"
  ): TypedContractMethod<
    [to: AddressLike, value: InEuint128Struct],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFromEncrypted"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: InEuint128Struct],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "ApprovalEncrypted"
  ): TypedContractEvent<
    ApprovalEncryptedEvent.InputTuple,
    ApprovalEncryptedEvent.OutputTuple,
    ApprovalEncryptedEvent.OutputObject
  >;
  getEvent(
    key: "TransferEncrypted"
  ): TypedContractEvent<
    TransferEncryptedEvent.InputTuple,
    TransferEncryptedEvent.OutputTuple,
    TransferEncryptedEvent.OutputObject
  >;

  filters: {
    "ApprovalEncrypted(address,address)": TypedContractEvent<
      ApprovalEncryptedEvent.InputTuple,
      ApprovalEncryptedEvent.OutputTuple,
      ApprovalEncryptedEvent.OutputObject
    >;
    ApprovalEncrypted: TypedContractEvent<
      ApprovalEncryptedEvent.InputTuple,
      ApprovalEncryptedEvent.OutputTuple,
      ApprovalEncryptedEvent.OutputObject
    >;

    "TransferEncrypted(address,address)": TypedContractEvent<
      TransferEncryptedEvent.InputTuple,
      TransferEncryptedEvent.OutputTuple,
      TransferEncryptedEvent.OutputObject
    >;
    TransferEncrypted: TypedContractEvent<
      TransferEncryptedEvent.InputTuple,
      TransferEncryptedEvent.OutputTuple,
      TransferEncryptedEvent.OutputObject
    >;
  };
}
